[workspace]
resolver = "2"
members = ["examples", "sanctum-macros"]


[workspace.dependencies]
heck = ">=0.4,<0.6"
proc-macro2 = "^1"
quote = "^1"
solana-program = ">=1"
syn = "^2"

# workspace members
sanctum-macros = { path = "./sanctum-macros" }
