[package]
name = "sanctum-macros"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = ">=0.1"
proc-macro2 = "^1"
quote = "^1"
solana-program = { version = "*" }
syn = "^2"
